### ISSUE TITLE
Add "Recycle Bin" Feature

### ISSUE THREAD

**Issue by ERROPiX** [Studio-42/elFinder#1065]
I think it's good idea to add a trash feature so deleted files can be recovered

**Comment by buckett** [comment]
This duplicate #129

**Comment by lokothodida** [comment]
Just putting out a sketch of how it could be implemented in a future release (without having looked too hard at the PHP connector), since there hasn't been much of a discussion on how to do this with 2.x+'s multi-root volumes:

* Have a local temp/trash directory that holds information about deleted files
  * For local file systems its easiest to just have the the folders/files themselves, but for other volumes it is probably best to store pseudo-information about the file/directory
* Have a volume "Recycle Bin" that points to said temp/trash directory
* Have the immediate sub-volumes/directories of the "Recycle Bin" volume correspond to the main volumes, e.g.

```
- Volume 1
- Volume 2
- Volume 3
- Recycle Bin
  - Volume 1
  - Volume 2
  - Volume 3
``` 
* Implement the connectors for each of the main volumes such that they have a "Recycle" action, which sends the appropriate amount of information to corresponding sub-volume in the temp/trash directory
* Also implement a "Restore From" action for each connector, which takes information about a deleted file/directory and restores it in that volume
* Then implement the "Recycle Bin" connector so that it has a "restore" action, which takes information about a given file and its volume and executes the "Restore From" action on that volume

**Comment by CodeLyokotEAM** [comment]
Can you devolop this feuture?

**Comment by CodeLyokotEAM** [comment]
Can you devolop this feuture?

**Comment by philippejadin** [comment]
An easer approach would be to rename deleted files, for example filename.extension.deleted or foldername.deleted

then disallow to delete .deleted files and folders
and then show it all with a grayed name for example, and allow to undelete.

Not so nice but not so hard to implement imho

**Comment by nao-pon** [comment]
I started to develop this function. By specifying the hash ID which becomes trash box in setting volume roots, when deleting items, move to trash box with original directory hierarchy.

**Comment by ERROPiX** [comment]
Hi @nao-pon 
Thank you for updating this issue, would it be good if the trash folder also have a "restore" feature, maybe using a hidden file to store the original folder path

**Comment by donShakespeare** [comment]
Good feature. Would there be one Recycle bin for each volume?

**Comment by nao-pon** [comment]
@ERROPiX The trash is mounted as one of the volumes, and when deleting, the directory hierarchy is reproduced to the volume and moved. To restore is re-move from the trash by the user's operation.

@donShakespeare The trash is specified by the hash value on elFinder as an option of each volume. You can specify the same one, but usually you specify another one.
