### ISSUE TITLE
I found some problem on elfinder 2.1

### ISSUE THREAD

**Issue by ichuot** [Studio-42/elFinder#1115]
I found some problem on elfinder 2.1:
**In ui/tree.js line 211:**
style="background-image:url(\''+dir.icon+'\')" . dir.icon is relative url. 
icon will not display correctly if 'img' dir is not place in root folder.
I think you should add css class for it

**In elfinder.css:**
.elfinder-cwd-view-icons .elfinder-cwd-filename {... white-space: pre-wrap; ...}
May be white-space: pre; is more exactly

**In elFinderVolumeLocalFileSystem.class.php line 62**
$this->getFullPath is not work on Windows system when 'path' option is absolute path
(sorry my english)

**Comment by nao-pon** [comment]
Hi @ichuot,

** about icon **

Please set absolute URL to option `icon`. However, I think a good idea to add a CSS class of options (for example `rootclass`).

** about white-space: pre-wrap **

Since the file name in the 2.1 two lines can be displayed has to `pre-wrap`. What problem are you having?

** about $this->getFullPath **

Please try the volume option `systemRoot`. (For example 'C: \', 'D: \', etc.)

**Comment by ichuot** [comment]
@nao-pon 

thank you for reply.

i found a small problem:
![filename](http://i.imgur.com/XdttrL6.jpg)

**about white-space: pre-wrap**
pre-wrap with 2 lines can not display "..." at last line.

**Comment by nao-pon** [comment]
**about icon**

I'll fix on next commit. It uses css class name.

**about &#8203;**

`&#8203;` It will be used for character wrapping. Value of the title attribute is a bug.It will be fixed next commit.

**about white-space: pre-wrap**
> pre-wrap with 2 lines can not display "..." at last line.

I am aware. However, no alternative is found.
