### ISSUE TITLE
onlyMimes not working

### ISSUE THREAD

**Issue by canbozdemir** [Studio-42/elFinder#1335]
I added like `onlyMimes: ['image']` or `onlyMimes: ['image/jpeg', 'image/pjpeg', 'image/png', 'image/gif']` , but didn't work.

**Comment by side-by-side** [comment]
Files mime types are checked at the server, so try to change the ```mimeDetect``` connector option (https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#mimedetect).

Today i had similar problem, when ```onlyMimes``` set to ```text/css``` didn't work as expected (filtered out css-files that should not).

The problem was at the server side: mime types was determined incorrectly. I changed ```mimeDetect``` connector option to ```internal``` and it solves the problem (on Windows, didn't check it an *nix yet).

You can see what mime types server set for each file by looking into server response. It is the first place where i had started to find the problem.

**Comment by nao-pon** [comment]
@canbozdemir I checked elFinder 2.1.11 with `onlyMimes: ['image']` or `onlyMimes: ['image/jpeg', 'image/pjpeg', 'image/png', 'image/gif']` of client configuration. It was work perfectly.

**Comment by canbozdemir** [comment]
@side-by-side i tried to add `mimeDetect` option as `internal` but i can't see any changes on UI.

and @nao-pon my elFinder version : 2.1.11

**Comment by nao-pon** [comment]
@canbozdemir I made example to `onlyMimes: ['image']`.

- http://hypweb.net/elFinder-nightly/demo/2.1/elfinder2.html
![bf70aa0f](https://cloud.githubusercontent.com/assets/1412630/14700909/48e207ec-07dd-11e6-85a1-8fbe5a3d3e6b.png)

**Comment by canbozdemir** [comment]
@nao-pon I'm working on ASP.NET MVC project so my service url different from yours. But I added the same codes in elfinder2.html and didn't work! :)

**Comment by StudioJunkyard** [comment]
is your `SERVICE_URL` actually referencing the connector for the language your using. for e.g., I'm using PHP, so I reference the `elfinder/php/connector.php`?

**Comment by side-by-side** [comment]
@canbozdemir, ```mimeDetect``` option is **connector** option (under root key) and should be set on server side, not in javascript. In my case ```mimeDetect``` by default was set to ```finfo``` and it caused to incorrect mime types for some files. After settin in to ```internal``` my problem was resolved. Just try.

Look at documentation: https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#mimeDetect.

**Comment by canbozdemir** [comment]
@side-by-side I downloaded ASP.NET MVC project from this link https://github.com/leniel/elFinder.Net . Then i used  `onlyMimes: ['image']` option like this and didn't work. So should i edit my server side code by mimeTypes paramater?

**Comment by side-by-side** [comment]
@canbozdemir, sorry i'm not familiar with ASP.NET. In my case with backend on PHP ```mimeDetect``` option worked out my issue with mime types. For example, without changing this option by default for css-files server determined mime-types differently: for some css-files it was ```text/x-c++```, for some correct ```text/css```. This issue is all about server. Client just tells a server that it should respond only with files that match specified mime-types.If server determines mime-types wrong — client will recive wrong files list.

**Comment by canbozdemir** [comment]
@side-by-side  ok bro thanks!

**Comment by side-by-side** [comment]
@canbozdemir, nothing bro :)
Wait for @nao-pon, he can tell you more than I.

**Comment by canbozdemir** [comment]
@nao-pon i am waiting support for ASP.NET MVC :)

Example project for **elFinder ASP.NET MVC** https://github.com/leniel/elFinder.Net

**Comment by StudioJunkyard** [comment]
His last comment on this was 5 hours ago. Do you think it might be possible that he's sleeping. Not everyone is online 24/7, lol.

**Comment by nao-pon** [comment]
It's really too bad, but I do not know ASP.NET. Please conside to use to PHP as  an option on the server.

**Comment by side-by-side** [comment]
@canbozdemir, so, at first place you should discover how **your** server determines files' mime-types.
Maybe there some similar server option, like ```mimeDetect```. I never worked with ASP.NET, I even didn't know that such elFinder version exists until today :)

**Comment by StudioJunkyard** [comment]
From what I can tell from looking at the source code for the links provided by @canbozdemir the .net implementation is similar to the PHP one, just in a different language. Mime-Type as has already been pointed at several times, is set in the connector file that's called via javascript in the server side file. The mime type's aren't set via Javascript, rather by the .net connecter server side, as it is using PHP.

**Comment by canbozdemir** [comment]
@side-by-side @nao-pon @StudioJunkyard thanks all! I will fix it on .NET MVC.

**Comment by StudioJunkyard** [comment]
@canbozdemir google is your friend, or more recently, Bing is the coder's friend. Apparently, they've been indexing code snippets. Good Luck in getting it working.

**Comment by troex** [comment]
close reason: not directly related to official connector
