### ISSUE TITLE
Input field as file type

### ISSUE THREAD

**Issue by mb202020** [Studio-42/elFinder#1423]
hello please how can i make input field as file type when you click on the browse open elfinder window and drag file from file manager in the field

**Comment by nao-pon** [comment]
@mb202020 You can use an client configuration option [`getFileCallback`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#getfilecallback).

e.g.
```javascript
getFileCallback : function(file) {
    $('#elfinderInput').val(file.mime);
}
```

DnD e.g.
```javascript
$('#elfinderInput').droppable({
	tolerance  : 'pointer',
	accept     : '.elfinder-cwd-file-wrapper,.elfinder-navbar-dir,.elfinder-cwd-file,.elfinder-cwd-filename',
	drop : function(e, ui) {
		ui.helper.hide();
		$(this).val(elfinderInstance.file(ui.helper.data('files')[0]).mime);
	},
	over : function(e, ui) {
		ui.helper.addClass('elfinder-drag-helper-plus');
	},
	out : function(e, ui) {
		ui.helper.removeClass('elfinder-drag-helper-plus');
	}
});
```

Here, it does not describe in detail because it is the development of the field. Further information, please ask in such [StackOverFlow](http://stackoverflow.com/questions/tagged/elfinder).
