### ISSUE TITLE
Error "Unable to connect to backend" during copy/paste operations.

### ISSUE THREAD

**Issue by ElrondVardamir** [Studio-42/elFinder#1705]
Hello everyone,

Very often i've got an error when I copy/paste some file : 
`Unable to connect to backend.
HTTP error 0`

Anyone can help me ?

Thank you.

**Comment by beechyrb** [comment]
I am having the same issue when uploading a file that is larger than around 500 pixels. It started happening when we updated to PHP 5.6
What version of PHP is installed on your server?

Rich

**Comment by nao-pon** [comment]
@ElrondVardamir , @beechyrb 

`HTTP error 0` meaning is "It could not connect to the back-end server.". I guess, this problem is that there is a cause to your client side or your server side.

Next article of the stack Ober flow will help you?

- [ajax - HTTP status code 0 - what does this mean in MS XMLHTTP? - Stack Overflow](http://stackoverflow.com/questions/872206/http-status-code-0-what-does-this-mean-in-ms-xmlhttp)

**Comment by aldemarcalazans** [comment]
Sometimes this error occurs when, inside a page requested with HTTP protocol, you have a Javascript code trying to make an HTTPS request. And vice-versa.
If you are still facing this problem, press F12 (or Ctrl + U) and take a look at the HTML code of the page. If you see something like that in your code:

<script>
var ajaxurl = "https://mydomain.com/wp-admin/admin-ajax.php";
(...)
</script>

And your page was requested in a manner similar to:

http://mydomain.com/2019/09/13/my-post/#elf_l1_Lw

You certainly will face this error.
