### ISSUE TITLE
elfinder in server error Readable volumes not available

### ISSUE THREAD

**Issue by gzai** [Studio-42/elFinder#1753]
Hello,

I have some issue,
my site with elfinder working so smoothly from begining, but when my server disable some function in php ( security issues ). my elfinder not working properly, it's say "Invalid backend configuration. Readable volumes not available.".

disable functions in php :
system, shell_exec, passthru, exec, phpinfo, popen, proc_open.

that functions disable now, but if elfinder not working properly, one by one that functions switch to enable and disable to check elfinder working again, and when all functions re-disable, elfinder working for now but after day not working again.

could you help us to find the solution?

**Comment by nao-pon** [comment]
@gzai What is result of next code on your server?

```php
<?php
$allowed = null;
$disabled = null;
$funcs = null;
if ($allowed = function_exists('proc_open')) {
	if ($disabled = ini_get('disable_functions')) {
		$funcs = array_map('trim', explode(',', $disabled));
		$allowed = ! in_array('proc_open', $funcs);
	}
}
var_dump(array($allowed, $disabled, $funcs));
```

**Comment by gzai** [comment]
@nao-pon 

this is the result
``
array(3) {
  [0]=>
  bool(false)
  [1]=>
  string(74) "show_source, system, shell_exec, passthru, exec, phpinfo, popen, proc_open"
  [2]=>
  array(8) {
    [0]=>
    string(11) "show_source"
    [1]=>
    string(6) "system"
    [2]=>
    string(10) "shell_exec"
    [3]=>
    string(8) "passthru"
    [4]=>
    string(4) "exec"
    [5]=>
    string(7) "phpinfo"
    [6]=>
    string(5) "popen"
    [7]=>
    string(9) "proc_open"
  }
}
``

**Comment by nao-pon** [comment]
elFinder only using `proc_open` in [elFinderVolumeDriver.class.php:procExec()](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeDriver.class.php#L5114) also procExec() called by [`getArchivers()`](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeDriver.class.php#L5429). Since the result of getArchivers () is stored in the session variable, problems may occur if the setting is changed while the session is in effect.

If you change the settings of the web server, please check with a new session.

**Comment by gzai** [comment]
the setting function proc_open change to enable, and it's work now.

i'll continue to pay attention for elfinder in my website still running after a day. and will tell if not working well.

Thank you :) @nao-pon
