### ISSUE TITLE
ElfinderSupportver1 problem when moving directories

### ISSUE THREAD

**Issue by MartinNu2** [Studio-42/elFinder#178]
Hi all,

When using the ElFinderSupportVer1 module I am experiencing a problem when dragging directories to another location.
The connector is moving the driectory to the new location, but the tree and content is not updated correctly.

Hope someone can help me out or point me in the right direction

Regards,

Martin.

**Comment by vongruenigen** [comment]
I'm also witnessing this issue currently after updating to version 2.1.12, is there any update on it?

**Comment by nao-pon** [comment]
I got it.

**Comment by nao-pon** [comment]
@vongruenigen Please try & check with [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by vongruenigen** [comment]
@nao-pon, thanks for your quick response! I still have the problem that my tree is broken after I moved a directory. The following screenshot shows how my tree breaks when moving the ... directory into the ... directory.

Before move:
<img width="957" alt="screen shot 2016-07-25 at 08 14 48" src="https://cloud.githubusercontent.com/assets/789513/17092050/feb8fd8a-523f-11e6-8ba8-732c985001b8.png">

After move (missing subdirectory in tree on directory "adftxt"):
<img width="959" alt="screen shot 2016-07-25 at 08 15 08" src="https://cloud.githubusercontent.com/assets/789513/17092056/08ad9c88-5240-11e6-942b-9ae6dd448777.png">

It's even worse when I try to move the original directory "blub" back to the root directory "Home".

Before:
<img width="956" alt="screen shot 2016-07-25 at 08 17 12" src="https://cloud.githubusercontent.com/assets/789513/17092086/410e8ad8-5240-11e6-8ce1-f6268c100e1e.png">

After:
<img width="958" alt="screen shot 2016-07-25 at 08 17 21" src="https://cloud.githubusercontent.com/assets/789513/17092087/44e75f0e-5240-11e6-8f48-806eaa86e045.png">

I cannot use the JSBin example I provided you in issue #1544 since it doesn't use the old API v1 proxy as far as I can see. Do you have another public instance of elFinder running where I could try to reproduce the issue?

**Comment by nao-pon** [comment]
@vongruenigen I made [JS Bin](http://jsbin.com/qayuta/edit?html,output) of PHP connector API 1.0. Please check it.

**Comment by vongruenigen** [comment]
@nao-pon, thanks, I'm going to try to reproduce the issue with this.

**Comment by vongruenigen** [comment]
@nao-pon, I tried to reproduce it, but it's not possible easily. Maybe the problem lies in our connector library (see the [el_finder](https://github.com/phallstrom/el_finder) ruby gem). I'm going to investigate that and get in touch with you as soon as I've found something.

**Comment by vongruenigen** [comment]
@nao-pon, it's definitely our backend which is causing the problem. I tested our frontend with the backend you provided me in the JSBin example earlier (see [here](http://jsbin.com/qayuta/edit?html,output)) and it worked like charm.

In this case, I'm going to open an issue on the issue tracker for the ``el_finder`` gem. Thanks a lot again, you can close this issue IMO.

**Comment by nao-pon** [comment]
I came up with one of the ideas. Please try newest nightly build.

**Comment by vongruenigen** [comment]
@nao-pon, it's definitely our backend, I just checked our code and figured out that we're not always sending the whole tree back to the client, even though we should. Your newest change wouldn't help in this situation, so IMO, you can close this issue as I'm going to fix this problem in our backend. Thanks for your support.

**Comment by nao-pon** [comment]
@vongruenigen You are welcome, don't worry. :-)
