### ISSUE TITLE
Using LocalFileSystem together with MySQL

### ISSUE THREAD

**Issue by logofakt** [Studio-42/elFinder#1808]
I'm starting to integrate elfinder into an existing software. References on files are already stored in a MySQL database and I would appreciate to do it with elfinder too.

Fortunatly there is a MySQL driver, I think it is for this purpose. Unfortunatly I did not find any information on how to use this driver even simultanusly with the LocalFileSystem.

Is there any help or information on this issue? Or is it enough to declare the array in connector.minimal.php?

Thanks for any help and best regards
Christian Lauer

**Comment by mungurs** [comment]
If I understood you correctly, then I had similar task. I went  a different path (because mysql support was dropped?) .
 I created a class for file sync., that is bound  to some events in elFinder `'bind' => ['mkfile rename duplicate upload rm paste' => [ [$this->fileSync, 'sync'] ]] `.
This class processes all events and saves file changes in database. 
Class example - https://gist.github.com/mungurs/1d2187332fdb5e72e64ada18a8fd9f3a

**Comment by logofakt** [comment]
Hi mungurs,
that's exactly what I was looking for, many thanks for this.
Christian Lauer

**Comment by SkyTaurus** [comment]
@mungurs Can you share Leaffile and fileManagerFacade classes ?

**Comment by mungurs** [comment]
Sure, nothing special in there. LeafFile comes from an older system, so use it as rough guide.
https://gist.github.com/mungurs/6f01ae5c00f6b2db19354b709b135217
https://gist.github.com/mungurs/4d73f0978385bfedc3fbcca601de0e3f
