### ISSUE TITLE
Local and live permission mismatch

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1861]
After somehow getting the root volumne locked on my local machine, and uploading the changes to a live server, there is a mismatch in permissions.

I got this working somehow on my local machine (Windows), but it is not working when deployed to a live server (Linux)

I have used if ($path === "/" || $path === "\\") to cover both bases, in my `accessControl` callback.

Oddly, on local, the root volume states Permissions: read, Locked: yes but the live server states Permissions: read and write, Locked: yes

Could this be a caching issue (like we've seen before with elFinder)?

**Comment by nao-pon** [comment]
@paulcanning Probably, continuation from #1687.

Since elFinder caches the root stat to session variables, it can be a problem if there is a change during one session.

Therefore, if it is possible to accept `rootRev` of the stat data and change during the session change the value.

However, caching with the FlySystem driver or GCS adapter can not be handled by elFinder.
