### ISSUE TITLE
Is there a method to optimize getting path information?

### ISSUE THREAD

**Issue by mcarpenterjr** [Studio-42/elFinder#2041]
Elfinder takes over a minute to finish "getting path information" when the `startPath` is in a large directory. Is there a way to improve the efficiency of elFinder when retrieving path information from a large directory?

**Comment by nao-pon** [comment]
@mcarpenterjr There is no fundamental solution at the moment. There is a related issue # 1879.

As a workaround you can try the `checkSubfolders` volume root option. (`false`: disable or` -1`: ondemand)

**Comment by mcarpenterjr** [comment]
Don't notice much of a change, should it be;
`'checkSubfolders' => '-1'` or `'checkSubfolders' => -1`
for clarification purposes.

**Comment by mcarpenterjr** [comment]
Related to this, when I look at my server stats and I make a request for a file (to download or open) the CPU of my server becomes saturated with 2 tasks from my apache user. So 2 questions, What is elFinder doing when it is getting path information? and Is there any way to turn off the File Tree view?

See we do a large amount of "testing" which is very document intensive reports are anywhere from 5 to 65meg pdfs and we deal with a large number of images, so in this implementation of elfinder I need users to be able to be brought to a file location where they will add or download from. The siblings of that location are not important, it's the children that are important.

elFinder is really helping us with this regardless.

**Comment by nao-pon** [comment]
Since the value of "checkSubfolders" is evaluated after converting it to an integer, `-1` or `"-1"` both is vaild.

It is unintended behavior that the CPU is consumed with `file` (download) or` open` (file open) commands. Since these commands are requested by specifying the target file, they are not usually heavily loaded. There may be bugs in something, but in my environment there is no problem.

Please let me know if you find a problem.

In [Nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip), request optimization at the time of directory tree acquisition is applied. Please try it too.
