### ISSUE TITLE
Feature Request: Meta data saving

### ISSUE THREAD

**Issue by hardcopi** [Studio-42/elFinder#2078]
Any chance elfinder can save meta data such as alt and title tags? For instance if the file is: image.jpg then the meta data would be something like image.json

**Comment by nao-pon** [comment]
@hardcopi There is no plan to add such functions in elFinder. It is possible to implement it yourself in the event handler.

Please check other issues - https://github.com/Studio-42/elFinder/search?q=meta+data&type=Issues&utf8=%E2%9C%93 .

**Comment by dleffler** [comment]
Or you might extend the elFinderVolumeLocalFileSystem class. With Exponent CMS, we do this to add file details which are stored in our mysql database. The file themselves remain on the server (I say this because the elFinder MySQL driver seems to be designed to store the file within the MySQL database.)
