### ISSUE TITLE
Multiple download disable zipdl

### ISSUE THREAD

**Issue by MickaelTH** [Studio-42/elFinder#2106]
Hi,

When user select multiple files, is it possible to download them 1 by 1 instead of a zip files?

https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#zipdl-api--21012

Thank you

**Comment by nao-pon** [comment]
@MickaelTH There is an option `disabled` of connector roots option. If you want to disable `zipdl` command, Please set `'disabled' => array('zipdl')`.

However, since I think that you may want to disable only downloading files while keeping directory zipdl enabled, I plan to add client option `commandOptions.download.minFilesZipdl`.

```javascript
commandOptions : {
		download : {
			// max request to download files when zipdl disabled
			maxRequests : 10,
			// minimum count of files to use zipdl
			minFilesZipdl : 1
		}
}
```

**Comment by MickaelTH** [comment]
Thank you for your answer and your enhancement. You are correct, folder download is nice feature that I want to keep.
