### ISSUE TITLE
Not work language in connect js file

### ISSUE THREAD

**Issue by q3dm0** [Studio-42/elFinder#2201]
I trying connect change language in my project with elfinder, but not work from version 2.1.26! 
I add lang variables this code

<script type="text/javascript" src="view/javascript/imagemanager/elFinder/js/i18n/elfinder. echo $language; .js"></script>

later add variables in this code 

$(document).ready(function() {	
	$('#elfinder').elfinder({
		width: '100%',
		lang: 'echo $language;',

and not change lang, works only in elfinder settings, in versions 2.1.25 lang variables work excellent

**Comment by nao-pon** [comment]
@q3dm0 In elFinder 2.1.26 and later, it supports automatic loading of language files. Also, the selected language is saved in the local storage of the browser, and that language is selected the next time.

In order to check whether the option set language is selected, initialize the user setting in preferences tab in help dialog.

**Comment by q3dm0** [comment]
how to return in 2.1.26 the work of variables as in 2.1.25, just need such a choice of language

**Comment by nao-pon** [comment]
To prohibit users from changing the language Please hide the language selection form in the style sheet.
```css
.elfinder-help-preference dd.elfinder-help-language { display: none; }
```

However, it is a bug that the option setting language is stored in the browser, so I will fix it.

**Comment by nao-pon** [comment]
@q3dm0 Thanks! 👍
