### ISSUE TITLE
Include elFinder in upcoming plugin version?

### ISSUE THREAD

**Issue by Offerel** [Studio-42/elFinder#2356]
As you might know, there is a Roundcube plugin from me, based on elFinder. This plugin is licensed under the AGPL license. Until now, I designed it so that you have to manually download and configure elFinder yourself. 

Would it be OK if I released elFinder directly together with the Roundcube plugin, i. e. if you download the plugin from Github, which is also pre-configured and downloaded with elFinder? This would certainly make it easier for most users. In the case of the Roundcube plugin there are no longer any references to Cloudflare and the CKEditor is also available in a local version.

If it is not OK, this also no problem, then users should download elFinder separate.

**Comment by nao-pon** [comment]
@Offerel elFinder is issued under a 3-clauses BSD license. Since there are no restrictions other than to satisfy that license provision, there is no problem with inclusion of elFinder unless it contravenes your product's license.

I think that it is more better if the update is easy by the user acquiring elFinder and overwriting it.

**Comment by Offerel** [comment]
Ok, thx for that info. In that case, i leave it so that the user can download elFinder separate.
