### ISSUE TITLE
input not clickable when dialog with modal:true is open

### ISSUE THREAD

**Issue by unigia** [Studio-42/elFinder#2545]
Hi, 
if i trasform some commands, like chmod in modal (modal:true), the text input aren't clickable in Firefox, because the focus event is caught from the overlay. 
I have check the z-index but it's corrent. I think isn't z-index problem. 
Thanks.

**Comment by nao-pon** [comment]
@unigia There is same problem in the[ nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip)? I checked it with nightly, but there aren't any problems.

**Comment by mananjobanputra** [comment]
This problem seems to have arrived sometime around Bootstrap 3.33 - prior to that things seemed to work just fine but starting with 3.34 and later things started going south. The problem is that many modern applications use fixed, absolute and relative positioning to lay out their user interface. The above problem occurs when the Modal dialog sits within a container that has any parent that uses either fixed, absolute or relative positioning. The change post 3.34 of bootstrap was that the modal overlay was moved to the DOM root below <body> while the actual modal dialog content in this case is sitting inside of a separate nested DOM structure.

You can solve this issue by below code.

$('body').on('show.bs.modal','.note-editor .modal', function () {
        $(this).appendTo("body");
 });
