### ISSUE TITLE
Questions about Security

### ISSUE THREAD

**Issue by neo314** [Studio-42/elFinder#2702]
So if I am using elFinder with Summernote in an administration area for a CMS, what do I need to do to prevent malicious access? If I require a session variable authentication to the PHP connector file (user logs into site, has a session value assigned as the token and the token is required in order to access the connector file), is that enough or are there other actions that need to be taken?

If I am using it as a plugin, are elfinder.html and elfinder.legacy.html a security issue in any way and are they even needed or used?

Thanks for the feedback.

**Comment by neo314** [comment]
nevermind. I found the Wiki howtos unless someone has more I should know.

**Comment by neo314** [comment]
I found the Wiki howtos. so my question now is how many ways do I need to secure? If I secure the Connector is that enough?

**Comment by nao-pon** [comment]
@neo314 

>  If I secure the Connector is that enough?

Yes, On the client UI side, mainly XSS countermeasures have been applied, and we are making efforts to ensure that the security holes on the client UI side are only those caused by the web browser. On the other hand, the security strength of the back end varies depending on your setting. Therefore please pay close attention to setting backend.
