### ISSUE TITLE
Change quicklook behavior to a basket list

### ISSUE THREAD

**Issue by jancarlopacanza** [Studio-42/elFinder#2719]
Basically, I want the current quicklook to be docked to the right side and give a list of selected files and not a preview and count of the selected files.

After doing this, we should have similar to this one,

![image](https://user-images.githubusercontent.com/8994631/47001470-1fc57c80-d15d-11e8-89a0-4149fcfc42a5.png)

**UPDATE:**

After digging up to the code, I achieved this by running through the fm.selectedFiles() and changed the content of template that I am appending to the info element inside the quicklook-info-data

![image](https://user-images.githubusercontent.com/8994631/47001693-a67a5980-d15d-11e8-8a09-3e93cc063b1f.png)

**Now the issue is** after selecting items in my current folder (items in the basket will be updated) then when I changed my folder basket is being emptied. 

How can the selected files remain in the basket even if I navigate through different folders?

Thanks!

**Comment by nao-pon** [comment]
@jancarlopacanza For item selection, the destination folder is first selected when the folder is moved, and when the CWD is switched, it becomes non-selected state. To continue selecting items Place an item in the clipboard with the Copy command. Clipboard data can be obtained with `fm.clipbord ()`.

**Comment by jancarlopacanza** [comment]
I will look into the copy command and `fm.clipboard()`

**Comment by nao-pon** [comment]
@jancarlopacanza Please use this.

```javascript
fm.clipboard(fm.selected());
var files = fm.clipboard();
```

**Comment by jancarlopacanza** [comment]
@nao-pon 

This one works fine but the browser hangs when selecting items.
`fm.clipboard(fm.selected());
var files = fm.clipboard();`

Also, I'm seeing another problem even if items remained in the basket, I get no files when I press the Download button.

Do you know any other way I can use to make this function like you are adding an item to cart that you can download whenever you want.

Thanks.

**Comment by nao-pon** [comment]
@jancarlopacanza The problem is that elFinder keeps the file cache only if it is CWD's or what is in the clipboard. So it seems better to create your own commands.

For example,
- Keep the selected file in its own variables with that command
     - `var keeps = [];`
     - `keeps.push (FileObject);` // Please check and remove duplicate registrations
- Create a UI that lists the file information held in that variable
     - something with your coding
- Call download command by user download action
     - `elFinderInstance.cache(keeps, 'add');` // add to cache
     - `elFinderInstance.exec('download', $.map(keeps, function() {return this.hash;});`

**Comment by jancarlopacanza** [comment]
@nao-pon - thank you for your time giving suggestions on how can I achieve my goal.

I found the method `unselectAll()` that is responsible for unselecting items every cwd . I have modified elfinder to meet my requirements.

I'm closing this now 👍
