### ISSUE TITLE
I can not upload many files successfully

### ISSUE THREAD

**Issue by ji-ryoo** [Studio-42/elFinder#2723]
Hello

I can not upload many files successfully

Version: 2.1.42 (2.1-src Nightly: 43f8621)

I can not successfully upload a folder containing 3000 folders and 20000 files by dragging and dropping.

After uploading, the files inside will appear outside the folder.
(File layout will be disturbed.)

In the case of few files, I can upload normally.

Since I want to upload a lot of files, I changed "requestType" from "get" to "post".

Also I changed php config "max_input_vars" and "max_file_uploads" to 50000.

How can I successfully upload?

Thank you.

**Comment by ji-ryoo** [comment]
I saw the issue
Issues with File and Folder Upload #2593

same situation...

i set the php config...
post_max_size = 500M
upload_max_filesize = 500M
max_file_uploads = 50000
/max_input_vars = 50000

**Comment by nao-pon** [comment]
Since elFinder is a file manager using a web browser and it is also via the network, we do not assume uploading items with such a large volume. In addition, the rollback function when communication is not stable is also very poor compared with OS file system. Therefore, please do not transfer at once, please divide and transfer it.
