### ISSUE TITLE
How to add pagination to elFinder

### ISSUE THREAD

**Issue by sabeti05** [Studio-42/elFinder#2746]
Hi,
I have a folder with a large number of images and elFinder can not load them, is there any setting or option to add a pagination to elFinder?

thanks

**Comment by johnfort** [comment]
A u have error on display?

**Comment by sabeti05** [comment]
Hi,
no, it just says "open folder..." and a loading icon.
I want to know is it possible to have pagination, for example every 100 images in a new page?

thanks

**Comment by johnfort** [comment]
@sabeti05 May be creating thumbnails ...
Increase server power. Or turn off the creation of thimbnails.
How many files do you have in the folder?

**Comment by nao-pon** [comment]
@sabeti05 The current elFinder does not have a mechanism to acquire page unit data from the back end.

see #1879 .

**Comment by nao-pon** [comment]
However, if processing on the server takes time, pagination is not a solution to this problem. Since the back end needs to sort the data according to instructions from the client and then send it after splitting it, it may be later than it is now.

Currently, on my test server, processing time of folders with about 6000 image files is about 12 seconds.

**Comment by johnfort** [comment]
Pagination is bad.
The driver can check how many files it received after "scandir". If there are a lot of them, then the client receives the entire list, but such data as size / type is only for the first ~ 100.
Spinners appear in the interface. Sorting is not available until full download.

As example...

**Comment by nao-pon** [comment]
I'm reluctant about pagination. elFinder client side processing time is considerably less than backend processing time. Because rendering in stages as needed instead of rendering all the items. Depending on the processing capacity of the client, processing time for folders with 10,000 items on low-end PCs is about 1.8 seconds. In fact it can be used conveniently by searching items by incremental search and narrowing down and displaying them.

**Comment by applibs** [comment]
Pagination is the way to go in my opinion, and it's commonly used by law when any amount of any data is large. So I absolutely agree with @sabeti05 .
I'm just figuring out how to load large amounts of data from an external source. I need to find and hunt for more search results and save time for the user. The way I envision it is that when I scroll down to the last item, an api is called that returns the next items.
