### ISSUE TITLE
I need custom confirmations. And ı have a question

### ISSUE THREAD

**Issue by UnreALi** [Studio-42/elFinder#2765]
Hi @nao-pon  and everyone. Firstly elfinder is awesome. Thanks for your efforts

I want to use the Local File System with MySQL.
I use bind to synchronize to the database.
`'bind' => ['mkfile rename duplicate upload rm paste' => array(\App\Http\Controllers\elfinderBind::class,'DatabaseSync')]`

Based on this example I made some progress
https://github.com/Studio-42/elFinder/issues/1808

I think I discovered a mistake.
Does not return content if a folder is duplicated.
When i review this file elFinder.class.php

https://github.com/Studio-42/elFinder/blob/5c9d502e698a8842efa2aabc893cb124c4959825/php/elFinderVolumeDriver.class.php#L4786-L4788

The contents of the replicated folder are reserved.
Is there a specific reason?

An also
I want to make a custom confirmations if there is a record in the file delete actions in the table
For example 
![example](https://user-images.githubusercontent.com/23552481/48223484-3b145800-e3a8-11e8-91b9-d7f73c935c59.PNG)
or other congirmations.
How can i do something like that.

In fact my purpose is to do cms and keep the files added to my articles in a separate table.
for example, I don't want my pictures to be lost when the name of a file changes
I'm trying to synchronize the elfinder to the database.
is this the best approach? or just sync pictures added to the article.
couldn't find the right approach and I'm afraid of the corruption of the synchronization.
for example uploading files with ftp or any error.

What do you recommend me about it.

Thanks for your help.

**Comment by nao-pon** [comment]
@UnreALi 

1.
```php
 if ($this->ARGS['cmd'] !== 'duplicate') { 
 	$this->added[] = $this->stat($path); 
 } 
```

Currently, processing is done with `elFinder::duplicate()`. However, since it is not a good method to judge by processing with `$ this->ARGS['cmd'] !== 'duplicate'`, I will fix this.

https://github.com/Studio-42/elFinder/blob/df0beb187ef6fa7bc0255cd7b5405fefa0e4bdd2/php/elFinder.class.php#L2124-L2156

2. Message catalog can be changed with JavaScript. Please change `elFinder.prototype.i18` before elFinder instance creation, or `elFinderInstance.messages` if created.

3. If you want to integrate with CMS, i recommend that you create a driver based on the MySQL driver.

e.g. https://github.com/nao-pon/xelfinder/blob/master/xoops_trust_path/modules/xelfinder/plugins/xelfinder_db/driver.class.php

**Comment by UnreALi** [comment]
Thank you so much for your help

I'm a bit foreign to the approach to keeping files in the database.
Will you help me understand.

For example
How can I send a picture to a web page.
If we send pictures by request.
Will the request sizes not be too much.
or
I'm using [glide ](http://glide.thephpleague.com/)to use a picture in multiple dimensions.
Can I use something like that?

I am completely foreign to such an approach.
Are there any projects that are already working on this issue and that I can review.

**Comment by nao-pon** [comment]
@UnreALi For example in my project [X-elFinder](https://github.com/nao-pon/xelfinder) ...

1. Parent-child relationships of items, permissions, references to file entities are managed in the [database](https://github.com/nao-pon/xelfinder/blob/master/xoops_trust_path/modules/xelfinder/sql/mysql.sql).
2. The entity of the file is outside the document root. In order to fully control the access rights of items.
3. Access to the file entity is done through PHP [connector](https://github.com/nao-pon/xelfinder/blob/master/xoops_trust_path/modules/xelfinder/connector.php) or [gateway](https://github.com/nao-pon/xelfinder/blob/master/xoops_trust_path/modules/xelfinder/main/view.php).
4. If the server supports X-SendFile etc., we use it to improve performance.
