### ISSUE TITLE
Not correct icon - java

### ISSUE THREAD

**Issue by RobiNN1** [Studio-42/elFinder#2873]
Java files has c++ icon 

![screen](https://user-images.githubusercontent.com/11664877/54352319-b2f1d800-4651-11e9-8fd3-ac7349955600.png)

And files with name like `c.c` doesn't show

v2.1.48

**Comment by nao-pon** [comment]
@RobiNN1 PHP's finfo seems to get the wrong MIME type. I will correct this.

I tried on the demo site about the file name "c.c" but it seems that there is no problem.

**Comment by RobiNN1** [comment]
I can't rename it
![screen1](https://user-images.githubusercontent.com/11664877/54438498-05f18b00-4737-11e9-9fcd-dacf56a437b8.jpg)
![screen2](https://user-images.githubusercontent.com/11664877/54438499-05f18b00-4737-11e9-96d2-39033ffd6bb4.jpg)
Weird bug, now I see this file

**Comment by RobiNN1** [comment]
There is lot of files with wrong MIME type
![screen](https://user-images.githubusercontent.com/11664877/54439087-63d2a280-4738-11e9-8c7b-09d96d4b7153.png)

**Comment by nao-pon** [comment]
@RobiNN1 I think that the file name "c.c" is not acceptable because of the connector setting. Check the [`acceptedName`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#acceptedname) option.

And, there are no problems with some MIME-Types of the files you have highlighted in red. Since the MIME-Type detected in the Info dialog is displayed, please check it.

![190316-212741](https://user-images.githubusercontent.com/1412630/54475243-76c99d80-4832-11e9-8adb-6fdf2c392562.png)

Some uncommon extensions are not included in the elFinder standard, so you can set options if you need their MIME-Type.

- [additionalMimeMap](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#additionalmimemap-elfinder--2122)
