### ISSUE TITLE
Don't have gallery viewer

### ISSUE THREAD

**Issue by Ange7** [Studio-42/elFinder#2940]
Hello,

On the demo of elfinder (here: https://studio-42.github.io/elFinder/#elf_l1_Lw) when i click on one picture and i click on « eye icon » i have a viewer with next & previous button. 

On my elFinder instance i don't have this viewer, when i click on « eye icon » i just have information about the file. 

Why ? is it a problem with my configuration ?

My version 

Version: 2.1.26, Version du protocole: 2.1026
jQuery/jQuery UI: 2.2.4/1.12.1

Thank you.

**Comment by nao-pon** [comment]
@Ange7 In order to preview an image file, it is necessary to get the URL of the file item correctly. Are your URL options correct in the connector volume settings?

**Comment by Ange7** [comment]
@nao-pon when I db click on file, the file is correctly downloaded so I guess the URL configuration is OK. Just preview not working...

**Comment by nao-pon** [comment]
@Ange7 As you can see on our demo site, when you double-click on an image file, the image will be displayed in a new window rather than downloaded. If the image is downloaded, you do not have inline permission.

Check the [`dispInlineRegex`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#dispinlineregex) configuration.

**Comment by Ange7** [comment]
Yes ! Thank you !
