### ISSUE TITLE
Wrong parameter for post request

### ISSUE THREAD

**Issue by Jamestoms** [Studio-42/elFinder#3083]
Hello, for the problem of too long URL, I changed the requestType to post, but the body of post request is still like this: "cmd=open&target=2F686F6D652F68706361646D696E&init=1&tree=1".How can I solve this problem? Thank you！
![problem](https://user-images.githubusercontent.com/30195437/71947130-cd132d00-3206-11ea-9a94-2948e1f6f20c.PNG)

**Comment by nao-pon** [comment]
@Jamestoms It looks like your settings are sending the POST method correctly. It's not a problem.

However, because the server is returning a 400 error, you need to resolve the cause on the server side.

Also, the transmitted data does not seem to be that of plain elFinder. Check out the other applications you are combining.

**Comment by Jamestoms** [comment]
OK, I'll check it again，thank you very much！
