### ISSUE TITLE
Invalid backend response. Error occurred on the server side. HTTP error 500 due to 12 directories and 115888 files in /home/user 

### ISSUE THREAD

**Issue by jaimbh** [Studio-42/elFinder#3554]
Whenever I open /home/user using elfinder, it gives:
Invalid backend response.
Error occurred on the server side.
HTTP error 500

This is happening because /home/user has 12 directories and 115888 files. The /home/user has a size of 5.5gb.
What do I need to add in the elfinder.php configuration file or any other file to solve this?

Below is $opts array in elfinder.php:
'roots' => array(
		// Items volume
		array(
			'driver'        => 'LocalFileSystem',         
			'path'          => $user['homedir'],       
			'statOwner' => true,
			'uploadAllow'    => array('all'),           
			'uploadOrder'   => array('allow', 'deny'),      
			'acceptedName' => 'validName',
			'tmbPath' => '',
			'maxArcFilesSize' => 'unlimited',
		),

**Comment by dleffler** [comment]
This usually happens with the PHP process -exceeds the 'max_execution_time' php server setting. This is highly likely based on the size of the folder...I haven't investigated it myself, but I don't believe elFinder adheres to it's client configuratoin 'showFiles', etc.. settings and tries to process the entire folder initially instead of as the rest of the folder's files are displayed? I could be misunderstanding the 'showFiles' setting purpose though.
