### ISSUE TITLE
[From China] elFinder 2.0 How to add an extra root

### ISSUE THREAD

**Issue by imdong** [Studio-42/elFinder#98]
Thank you elFinder, it is useful, I like it.
However, I have a question, like to seek your help.
How can the same as your demo site, it adds a second root directory.
http://elfinder.org/
I hope there is a private, public display.
The other is free to upload.
Appreciate your help.

If you can, I hope that the answer can be more detailed.

汉语：
很感谢您的elFinder，它很好用，我很喜欢它。
但是，我有一个疑问，像寻求您的帮助。
如何才能像您的演示站点一样，为它添加第二个根目录。
我希望有一个是私用，公开展示的。
另一个是自由上传的。
很感谢您的帮助。
如果可以，我希望答案可以详细一些。

Thanks Google Translate

**Comment by uFlock** [comment]
I have a really thick question, but how do I disable Deleting/Renaming the first level of folders in root?

For Example if my root path is **path/to/files** then I want to prevent the user from being able to delete/rename  the first level of folders after the root  **path/to/files/first_level_folder**, but the user should be able to have full control inside the **path/to/files/first_level_folder/Subfolders**.

I tried doing:

            'attributes' => array(
                                array(
                                        'pattern' => '/^*/', //You can also set permissions for file types by adding, for example, .jpg inside pattern.
                                        'read'    => true,
                                        'write'   => false,
                                        'locked'  => false,
                                        'hidden'  => false
                                    )
                                )

But it has no effect whatsoever - i can still delete and rename first level folders. Am i missing the point completely as always?

Thank you for your time.

**Comment by sauerlu** [comment]
Dear sirs,

I want use elfinder with multiple roots in my editor for Joomla
The editor has the option to select an Image folder per group. So far everything works fine.
But when I add a second root folder in the connector.php of elfinder, this one appears only if your administrator of the joomla site.

My controller looks like this:

<?php
defined( '_JEXEC' ) or die;
error_reporting(0); // Set E_ALL for debuging

include_once JPATH_ROOT.'/plugins/editors/yeeditor/assets/js/ckeditor/elfinder/php/'.'elFinderConnector.class.php';
include_once JPATH_ROOT.'/plugins/editors/yeeditor/assets/js/ckeditor/elfinder/php/'.'elFinder.class.php';
include_once JPATH_ROOT.'/plugins/editors/yeeditor/assets/js/ckeditor/elfinder/php/'.'elFinderVolumeDriver.class.php';
include_once JPATH_ROOT.'/plugins/editors/yeeditor/assets/js/ckeditor/elfinder/php/'.'elFinderVolumeLocalFileSystem.class.php';
// Required for MySQL storage connector
// include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeMySQL.class.php';
// Required for FTP connector support
// include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeFTP.class.php';


/**
 * Simple function to demonstrate how to control file access using "accessControl" callback.
 * This method will disable accessing files/folders starting from  '.' (dot)
 *
 * @param  string  $attr  attribute name (read|write|locked|hidden)
 * @param  string  $path  file path relative to volume root directory started with directory separator
 * @return bool|null
 **/
function access($attr, $path, $data, $volume) {
	return strpos(basename($path), '.') === 0       // if file/folder begins with '.' (dot)
		? !($attr == 'read' || $attr == 'write')    // set read+write to false, other (locked+hidden) set to true
		:  null;                                    // else elFinder decide it itself
}

//Get select image folder by option
$elfinderfolderaccess = array_filter(json_decode(get_yeeditor_option('yeeditor_elfinderfolderaccess','[]'),false));
$user = JFactory::getUser();
$imagefolder = "images/";
foreach($user->groups as $group){
	if(isset($elfinderfolderaccess[$group])){
		$imagefolder = $elfinderfolderaccess[$group]."/";
	}
}

$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
			'path'          => JPATH_ROOT.'/'.$imagefolder,         // '../files/',         // path to files (REQUIRED)
			'URL'           => JURI::root().$imagefolder,        //dirname($_SERVER['PHP_SELF']) . '/../files/',  // URL to files (REQUIRED)
			'alias'         => 'First home',
			'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
			'mimeDetect'    => 'mime_content_type',
			'uploadDeny'    => array('text/x-php'),
			'disabled' => array('mkfile', 'edit')
		),
		array(
			'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
			'path'          => JPATH_ROOT.'/'.$imagefolder.'/gallery/',         // path to files (REQUIRED)
			'URL'           => JURI::root().$imagefolder.'/gallery/',        //dirname($_SERVER['PHP_SELF']) . '/../files/',  // URL to files (REQUIRED)
			'alias'         => 'Gallery',
			'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
			'mimeDetect'    => 'mime_content_type',
			'uploadDeny'    => array('text/x-php'),
			'disabled' => array('mkfile', 'edit')
		)
	)
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();

There you can see the function "elfinderfolderaccess" is used.

This function looks like this:

public static function elfinderfolderaccess($value_arr, $checkSuperAdmin = false)
	{
		static $count;

		$count++;

		$isSuperAdmin = JFactory::getUser()->authorise('core.admin');

		$db = JFactory::getDbo();
		$query = $db->getQuery(true)
			->select('a.*, COUNT(DISTINCT b.id) AS level')
			->from($db->quoteName('#__usergroups') . ' AS a')
			->join('LEFT', $db->quoteName('#__usergroups') . ' AS b ON a.lft > b.lft AND a.rgt < b.rgt')
			->group('a.id, a.title, a.lft, a.rgt, a.parent_id')
			->order('a.lft ASC');
		$db->setQuery($query);
		$groups = $db->loadObjectList();

		$html = array();

		for ($i = 0, $n = count($groups); $i < $n; $i++)
		{
			$item = &$groups[$i];

			// If checkSuperAdmin is true, only add item if the user is superadmin or the group is not super admin
			if ((!$checkSuperAdmin) || $isSuperAdmin || (!JAccess::checkGroup($item->id, 'core.admin')))
			{
				// Setup  the variable attributes.
				$eid = $count . 'group_' . $item->id;

				// Don't call in_array unless something is selected
				$value = '';

				if ($value_arr && isset($value_arr[$item->id]))
				{
					$value = $value_arr[$item->id];
				}

				$rel = ($item->parent_id > 0) ? ' rel="' . $count . 'group_' . $item->parent_id . '"' : '';

				// Build the HTML for the item.
				$html[] = '	<div class="control-group">';
				$html[] = '		<div class="controls">';
				$html[] = '			<input type="text" class="group-folder" data-id="'.$item->id.'" value="'.$value.'" />';
				$html[] = '			' . str_repeat('<span class="gi">|&mdash;</span>', $item->level) . $item->title;
				$html[] = '		</div>';
				$html[] = '	</div>';
			}
		}

		return implode("\n", $html);
	}


Can someone help me to modify this function, so that every group gets his own root (Alias First Home) AND the 2nd root (alias Gallery) of Elfinder.

Thanks a lot for your help. Sorry I'm realy a Newbie...

**Comment by paulcanning** [comment]
@uFlock try '/^.+/' for your pattern
